package NegozioPackage.GUI;


import NegozioPackage.*;

import javax.swing.*;
import java.awt.*;


public class Bill extends JFrame {
    private JPanel mainPanel;
    private JLabel labelTitolo;
    private JPanel panelTItolo;
    private JPanel panelScontrino;
    private JPanel scontrinoPanel;
    private JLabel scontrinoLabel;
    private JScrollPane scorollScontrino;

    StrategiaPagamento pagamentoStrategy;

    public Bill(StrategiaPagamento pagamentoStrategy) {

        this.pagamentoStrategy = pagamentoStrategy;
        scontrinoLabel.setText(pagamentoStrategy.stampaScontrino());

        add(mainPanel);
        setSize(500, 500);
        setVisible(true);

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        panelTItolo = new JPanel();
        panelTItolo.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panelTItolo, gbc);
        labelTitolo = new JLabel();
        labelTitolo.setFont(new Font(labelTitolo.getFont().getName(), labelTitolo.getFont().getStyle(), 18));
        labelTitolo.setText("Scontrino ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelTItolo.add(labelTitolo, gbc);
        panelScontrino = new JPanel();
        panelScontrino.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panelScontrino, gbc);
        scontrinoPanel = new JPanel();
        scontrinoPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panelScontrino.add(scontrinoPanel, gbc);
        scorollScontrino = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        scontrinoPanel.add(scorollScontrino, gbc);
        scontrinoLabel = new JLabel();
        scontrinoLabel.setText("");
        scorollScontrino.setViewportView(scontrinoLabel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
