package NegozioPackage.GUI;

import NegozioPackage.PagamentoAbstractStrategy;
import org.omg.CORBA.PUBLIC_MEMBER;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ReportRicerca extends JFrame {
    private JPanel mainPanel;
    private JButton okButton;
    private JLabel risultatiLabel;
    private JLabel titoloLabel;
    private JPanel buttonPanel;
    private JPanel risultatiPanel;
    private JPanel titoloPanel;

    public ReportRicerca(String stampare) {
        super("Report Ricerca");

        risultatiLabel.setText(stampare);

        okButton.addActionListener(new AscoltaOk());

        add(mainPanel);

        pack();

        Dimension dim = this.getSize();
        double x = dim.getWidth();
        System.out.println(getX());

        setSize((int) x, 200);
        setResizable(false);
        setVisible(true);

    }

    public void setData(ReportRicerca data) {
    }

    public void getData(ReportRicerca data) {
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        titoloPanel = new JPanel();
        titoloPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(titoloPanel, gbc);
        titoloLabel = new JLabel();
        titoloLabel.setFont(new Font(titoloLabel.getFont().getName(), titoloLabel.getFont().getStyle(), 18));
        titoloLabel.setText("Risultati RicercaEffettuata");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        titoloPanel.add(titoloLabel, gbc);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(buttonPanel, gbc);
        risultatiPanel = new JPanel();
        risultatiPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        mainPanel.add(risultatiPanel, gbc);
        risultatiLabel = new JLabel();
        risultatiLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        risultatiPanel.add(risultatiLabel, gbc);
        okButton = new JButton();
        okButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(okButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public class AscoltaOk implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            setVisible(false);
            dispose();
        }
    }

}
